CREATE TABLE MEMBER(
	MID	VARCHAR(50) PRIMARY KEY,
	MPW VARCHAR(20),
	MNAME VARCHAR(30),
	MNICK VARCHAR(30) NOT NULL,
	MEMAIL VARCHAR(50) NOT NULL,
	MBIRTH VARCHAR(20),
	PHONE VARCHAR(20)
);
select * from member;
DELETE FROM MEMEBER WHERE MID='admin2';
CREATE TABLE ITEM(
	IID VARCHAR(50) PRIMARY KEY,
	IIMG VARCHAR(2000) NOT NULL,
	INAME VARCHAR(100) NOT NULL,
	IPRICE VARCHAR(50) NOT NULL,
	ICATEGORY VARCHAR(50) NOT NULL,
	ICNT INT DEFAULT 0,
	IDATE DATETIME NOT NULL
);

SELECT * FROM ITEM;
DROP TABLE ITEM;
SELECT * FROM ITEM WHERE LOCATE('053010',IID) LIMIT 0,20;
CREATE TABLE PET(
	PID INT AUTO_INCREMENT PRIMARY KEY,
	PNAME VARCHAR(20) NOT NULL,
	PVARITY VARCHAR(20) NOT NULL,
	PAGE VARCHAR(20) NOT NULL,
	PWEIGHT VARCHAR(20) NOT NULL,
	PBIRTH VARCHAR(20) NOT NULL,
	MID VARCHAR(50) NOT NULL,
	CONSTRAINT MEMBER_PET FOREIGN KEY(MID) REFERENCES MEMBER(MID) ON DELETE CASCADE 
);

CREATE TABLE ADDRESS(
	AID INT AUTO_INCREMENT PRIMARY KEY,
	MID VARCHAR(50) NOT NULL,
	ADDRESS VARCHAR(100) NOT NULL,
	ANAME VARCHAR(50) NOT NULL,
	APHONE VARCHAR(50) NOT NULL,
	AFLAG VARCHAR(1),
	CONSTRAINT MEMBER_ADDRESS FOREIGN KEY(MID) REFERENCES MEMBER(MID) ON DELETE CASCADE
);
SELECT*FROM MEMBER;
DELETE FROM MEMBER WHERE MID='sonpill5000@naver.com';
SELECT * FROM ADDRESS;
DROP TABLE ADDRESS;
SELECT * FROM BUYLIST;
CREATE TABLE REVIEW(
	RID INT AUTO_INCREMENT PRIMARY KEY,
	IID VARCHAR(50) NOT NULL,
	MID VARCHAR(50) NOT NULL,
	WRITER VARCHAR(50) NOT NULL,
	CONTENT VARCHAR(200) NOT NULL,
	STAR FLOAT(10) DEFAULT 0,
	RIMG VARCHAR(100),
	CONSTRAINT MEMBER_REVIEW FOREIGN KEY(MID) REFERENCES MEMBER(MID) ON DELETE CASCADE
);
SELECT * FROM ITEM WHERE LOCATE('사료',CONCAT(ICATEGORY,INAME)) LIMIT 0,12;
SELECT I.* FROM BUYLIST B INNER JOIN ITEM I ON B.IID=I.IID INNER JOIN MEMBER M ON B.MID=M.MID WHERE B.MID='admin1' ORDER BY BID DESC LIMIT 1,5;
DROP TABLE REVIEW;
SELECT * FROM REVIEW;
DELETE FROM REVIEW WHERE RID=4;
DELETE FROM REVIEW WHERE mid='admin1';
CREATE TABLE BUYLIST(
	BID INT AUTO_INCREMENT PRIMARY KEY,
	IID VARCHAR(50) NOT NULL,
	MID VARCHAR(50) NOT NULL,
	CONSTRAINT MEMBER_BUYLIST FOREIGN KEY(MID) REFERENCES MEMBER(MID) ON DELETE CASCADE
);

SET foreign_key_checks = 1;
SHOW TABLES;
DROP TABLE ITEM;
select * from item where locate("053008",iid);
DELETE FROM MEMBER WHERE MID='SON'; 
SELECT now();
SELECT * FROM ITEM WHERE IID LIKE '053%';
SELECT * FROM ITEM ORDER BY IDATE DESC LIMIT 0,5;
alter table item max_rows=100000000 avg_row_length=60240000000;
SELECT COUNT(*) FROM ITEM;
SELECT * FROM ITEM ORDER BY IID DESC;
SELECT  
    table_name, engine, table_rows AS tbl_rows,
    avg_row_length AS rlen,  
    floor((data_length+index_length)/1024/1024) AS allmb,  
    floor((data_length)/1024/1024) AS dmb, 
    floor((index_length)/1024/1024) AS imb   
FROM 
    information_schema.tables  
WHERE
    table_schema=database()  
ORDER BY
    (data_length+index_length) DESC;  

 SELECT * FROM ITEM WHERE ICATEGORY='건식사료';